"""add table User.tg_id big integer

Revision ID: fa81fba4dd55
Revises: 982ff90a889a
Create Date: 2023-08-14 12:03:03.208803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa81fba4dd55'
down_revision: Union[str, None] = '982ff90a889a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
